### ISSUE TITLE
Switch the upload bar when compressing

### ISSUE THREAD

**Issue by dgorges** [schmitzal/tinyimg#11]
A backendmodule where images are listed with a failed- or successtate. A label or state if the script works would be helpful and a nice to have feature would be to show how many percents have been saved with the compression.

**Comment by schmitzal** [comment]
Hi and thank you for your feature request!

A list of all images in the system could be really large if it's a big website. So we would need some sort of filtering or search. I need to think about that a bit more.

What I have planned to implement (if possible) is a "compressing" label on the upload progress bar, after the image got uploaded and compression started. Maybe followed by a "Compression saved you X% of your file size". Currently its staying at 100% while compressing which can take a few seconds.
And at the moment it's only possible to see if compression is working by checking the file size before and after.

**Comment by dgorges** [comment]
Hi Alex, 
this list ist kind of large that is true. The main problem is when the ext is installed I am missing a feedback if the ext works. If the connection to tinypng is fine and how many percents of my images have been compressed. To test if an image is compressed and compare the image is a big of hard work if you have a large page. But the idea with the compressing button is a good one.

**Comment by schmitzal** [comment]
Feature completed but it's only working with TYPO3 8.7 as I'm not able to override the filelist module template on TYPO3 7.6.

![2017-10-09_1748](https://user-images.githubusercontent.com/2011229/31386455-24b31a64-adc7-11e7-9892-0da9abc56f44.png)
![2017-10-09_1714](https://user-images.githubusercontent.com/2011229/31386456-24cc572c-adc7-11e7-849e-c623bc7da936.png)
