### ISSUE TITLE
Notification when compression limit is reached

### ISSUE THREAD

**Issue by schmitzal** [schmitzal/tinyimg#16]
Notify the editor on upload  when the compression limit is reached and don't ouput file upload as failed.

**Comment by schmitzal** [comment]
The tinify API is currently working on creating a function which returns the monthly compression limit. This feature should be available on August this year.

**Comment by ayacoo** [comment]
https://tinypng.com/developers/reference#compression-count Can you work with this reference?

**Comment by schmitzal** [comment]
This just returns how many compressions have been done but not how much are still available. The team behind of Tinypng/Tinify API is releasing a new version soon, which makes it possible to get the compression count.

**Comment by schmitzal** [comment]
Closed, as it doesn't look like this feature will ever be released by the team.
