### ISSUE TITLE
Minify processed images

### ISSUE THREAD

**Issue by hirnschmalz** [schmitzal/tinyimg#19]
After digging into your extension i recognized that only the original images are minified but not the processed ones. So I did some testing with processed images.

The file was processed with the `f:image` ViewHelper to create a variant with a maximum width of 800 pixels.

First the test without any minification

| File  | Size | Comment |
| --- | --- | --- |
| Original  | 3.98MB |
| Processed  | 120KB |
| Processed minified | 104.5KB | Manually minified via Webinterface | 

After that a test with the extension installed and the minified source file

| File  | Size | Comment |
| --- | --- | --- |
| Original | 1.36MB |
| Processed | 114KB |
| Processed minified | 104.2KB | Manually minified via Webinterface |

As you can see the file processed by TYPO3 is only slightly smaller with/without a minified source file. But minifiying the processed file saves around 10% in my testcase. The difference will be bigger with larger variants.

From my point of view it would make sense to have (at least) an option to enable minifying of processed files. What do you think?

I guess the correct way to do this would be the `postFileProcess` signal in `\TYPO3\CMS\Core\Resource\Service\FileService` on line `94`.

**Comment by schmitzal** [comment]
First of all, thanks for investigating! :)

Of course, it would be the best solutions to minify every processed image, but that would possibly mean a huge amount of compressions. The tinify API is limited to 500 free compressions per month. When processed images would be compressed, it would reach this limit much faster than without.

I'm not sure if understand your testcases right.
One of my test cases was the following:

| File  | Size | Comment |
| --- | --- | --- |
| Original File before upload  | ~4MB | Size: 1920x1024px |
| Compressed version after upload (using tinyimg)  | ~270KB | Size: 1920x1024px |
| Processed image after compression | ~50KB | Scaled down to 600px width | 

In a later version I'm thinking about adding a second compression tool without limit. At this point it would make sense to add the option of compressing processed images.
But this feature will take a while, as I'm currently developing a command controller which compresses already existing images.

**Comment by hirnschmalz** [comment]
We will have to implement such kind of image processing for one of our customers, so I just wanted to hear your opinion. I can imagine to make a fork of your `feature/compression-task` branch and start from there. In this case you could re-use our code (I've to talk to our customer first, but that would be my idea).

Two more questions

* What happens if the 500 free API calls are used? Do you just not minify the image and use the original image or will there be an error?
* What ab out ICC profiles? Do you know if tinypng respects embedded ICC profiles?

**Comment by schmitzal** [comment]
When will you start developing this feature? Currently, the feature/compression-task branch isn't stable. Better would be if you could wait until the feature is done. I'm very busy with work and stuff at the moment, but doing my best to release this feature as soon as possible.

With the next release, there will be a message that the compresion limit is reached, but the image will be uploaded anyway. In the current release it outputs an error message but the image is uploaded, as the compression triggers right after beeing uploaded.
I do not know if ICC profiles are repected from the tinify API, sorry. You could write an email to the Tinypng-Team. They are very kind and helpful.

**Comment by hirnschmalz** [comment]
I'll do some more evaluation and talk to our client and keep you updated.

**Comment by schmitzal** [comment]
That's great. Thanks! :)

**Comment by schmitzal** [comment]
Nothing new here. Closed.

Feel free to reopen it.

**Comment by Mainbird** [comment]
@schmitzal I think this is still relevant and would be a nice feature. :)

How about a command that compresses processed images by a given limit? That way users on a free plan can schedule the image compression via task configuration to control it a bit and get compressed processed images from time to time.

**Comment by schmitzal** [comment]
@Mainbird 

I'm still not sure if there is need for this feature.
Do you have a case where a compressed image is getting bigger after being processed?
With the added command it's possible to compress all images in an existing project. After that, you could delete and rebuild every processed image, so they are generated from the compressed image.

I feel like running over processed image is needless compressions on tinypngs side.

But feel free to share your thoughts. I'm open to look into improving this. Maybe it would be a better solution to delete all related processed images of the current compressed file and rebuild them. But I have to look if this is possible with TYPO3.

**Comment by Mainbird** [comment]
@schmitzal I don't think the processed images are larger than the compressed original, but I haven't checked yet, but the processed images generated by ImageMagick or GraphicsMagick might still be compressed.

I think you can check this by uploading a processed image file manually to tinypng.
