### ISSUE TITLE
Working with ext image_autoresize

### ISSUE THREAD

**Issue by bocianl** [schmitzal/tinyimg#23]
Hello, thanks for the great extension.

I have some questions - is this ext can run with image_autoresize?
And another question - what about files that are resized by TYPO3 - this images are also compressed by tinyimg?

**Comment by schmitzal** [comment]
Hi,

never worked with image_autoresize, but will have a look at it how it works and if it triggers the signal slots used by tinyimg.
Processed files aren't compressed, as if so, everyone would reach the tinify free monthly compression limit really fast. But the source files are compressed and an image which is downscaled by TYPO3/Imagemagick wont get bigger. It get's even smaller as less size = less pixels and bytes. 
An example test I made:
- Original image: width 1920px - size ~2 MB
- Compressed image: width 1920px - size ~250kb
- Resized image: width 500px - size ~50kb

Pretty good result I think.

I'll come to you, when I had time to check the compability with ext image_autoresize. Meanwhile, if you got the time, you could just test it :)

Best regards and have nice weekend.

Alex

**Comment by bocianl** [comment]
Hi,
Yes, I already test it. It's not working with ext image_autoresize.

About processed files - good to know - thank you.

I think everyone got two problems with the editors - they upload too big images and not compressed. One of these problems your ext solves :)
