### ISSUE TITLE
Internal Server Error when uploading file

### ISSUE THREAD

**Issue by webdev2027** [schmitzal/tinyimg#41]
Hi Alessandro, I've installed your extension via EM, include the static TS-template (root), insert the API-key at the settings via Extension Manager. Your installation and configuration hints are very clear. I'm using `TYPO3 8.7.22` and `PHP 7.1` on a managed Server (1&1).

Unfortunately, I still have an error uploading a file. The upload finishes with an Internal Server Error:
![bildschirmfoto 2018-12-21 um 16 51 30](https://user-images.githubusercontent.com/5501876/50351139-8a21e100-0541-11e9-8c43-870ae7fda58c.png)

But if I reload, I'll can see the file is there, but not compressed.
![bildschirmfoto 2018-12-21 um 16 51 08](https://user-images.githubusercontent.com/5501876/50351201-b76e8f00-0541-11e9-9edf-f43016c76d05.png)

The same picture should be minimized to 240kb.
![bildschirmfoto 2018-12-21 um 16 20 34](https://user-images.githubusercontent.com/5501876/50351320-0f0cfa80-0542-11e9-9932-53243e5fad50.png)

I've read all the closed issues, but I think I'm the first, who have this problems?!
Is the fault with me or my configuration? Can you help me? 

Thanks, 
Stefan

**Comment by schmitzal** [comment]
Happy new year Stefan!

Which version of tinyimg are you using? Could you have a look at the Backend Module "Log" after uploading a file and see if there is any error showing up? Or you could look at the "Network" tab in you browser developer tools and then upload the file. A XHR request should come up and show an error under the "Preview" tab of this request.

**Comment by webdev2027** [comment]
Hi Alessandro - happy new year! Thanks for your reply. I'm using `TYPO3 8.7 LTS`and the latest `tinyimg 1.3.0`, installed via EM.

There's no error in Log, after uploading file. After checking the Filelist again, I see the uploaded image - but there's not compressed. So the upload is working, but not the compression.

I've checked the developer tools, after uploading the image there's a 200- and 500-status. Is this helpful?
![bildschirmfoto 2019-01-07 um 13 17 35](https://user-images.githubusercontent.com/5501876/50767933-f2c9c700-127e-11e9-8f7d-b8ebff224f9e.png)

Thanks, Stefan

**Comment by ayacoo** [comment]
@schmitzal Maybe its helpful, also for you, to implement an"tinify check"? So you can address such a problem or give a matching error message?

**Comment by webdev2027** [comment]
> Hello Stefan,
> full support for installations via extension manager has been dropped with version 1.3.0.
> So using this version won't work, without installing the tinify package manually (see [README](https://github.com/schmitzal/tinyimg/blob/master/README.md#installation-via-extension-manager)).
> If you click on the 500 request in the network tool and open up the preview tab it should show an error of a missing tinify class.

Hello Alessandro .. uhhh my fault. Excuse me I did not read the documentation carefully. So, my TYPO3-Project is not a Composer-Project, so I have no chance to use your extension, right? You have to install `tinify` also with `composer` - that's the problem. And I also use a managed Server from 1&1. Thanks for your patience ...

**Comment by webdev2027** [comment]
> Hello Stefan,
> full support for installations via extension manager has been dropped with version 1.3.0.
> So using this version won't work, without installing the tinify package manually (see [README](https://github.com/schmitzal/tinyimg/blob/master/README.md#installation-via-extension-manager)).
> If you click on the 500 request in the network tool and open up the preview tab it should show an error of a missing tinify class.

Hello Alessandro .. uhhh my fault. Excuse me I did not read the documentation carefully. So, my TYPO3-Project is not a Composer-Project, so I have no chance to use your extension, right? You have to install `tinify` also with `composer` - that's the problem. And I also use a managed Server from 1&1. Thanks for your patience ... 

.. I see the manual installation, so I give it a try : https://tinypng.com/developers/reference/php

**Comment by schmitzal** [comment]
> @schmitzal Maybe its helpful, also for you, to implement an"tinify check"? So you can address such a problem or give a matching error message?

Sure. I'll add this to my roadmap, thanks :)

**Comment by schmitzal** [comment]
> > Hello Stefan,
> > full support for installations via extension manager has been dropped with version 1.3.0.
> > So using this version won't work, without installing the tinify package manually (see [README](https://github.com/schmitzal/tinyimg/blob/master/README.md#installation-via-extension-manager)).
> > If you click on the 500 request in the network tool and open up the preview tab it should show an error of a missing tinify class.
> 
> Hello Alessandro .. uhhh my fault. Excuse me I did not read the documentation carefully. So, my TYPO3-Project is not a Composer-Project, so I have no chance to use your extension, right? You have to install `tinify` also with `composer` - that's the problem. And I also use a managed Server from 1&1. Thanks for your patience ...
> 
> .. I see the manual installation, so I give it a try : https://tinypng.com/developers/reference/php

If this managed server doesn't come with composer you will have to install the package manually and get it to work. Could be a bit tricky. Ever better would be, to build the project on a server with composer (or on a local maschine) and deploy it to the server once builded.

**Comment by webdev2027** [comment]
Hi Alessandro, today I've install your extension via composer and It works great. Thank you. You can close this issue.

**Comment by schmitzal** [comment]
Great to hear.
If you experience any further issues with the extension, feel free to open a new issue.
