### ISSUE TITLE
(Internal Server Error) Upload of file image.png

### ISSUE THREAD

**Issue by arunspawoz** [schmitzal/tinyimg#49]
Hello Team,

I am trying to use this extension in my website and I am facing a strange issue when the image uploaded. It returns "Internal Server Error".

When I checked the system log, I can see that there is an error there. Please see the screen below.

![error](https://user-images.githubusercontent.com/20816321/71766367-5daaee00-2f25-11ea-8fde-6900fa8da755.png)

I hope this will be the issue. Somebody can give me a hint how can I solve this problem? I am using the latest version of the extension.

Thank you.

**Comment by schmitzal** [comment]
Hello @arunspawoz and happy new year!

are you running your TYPO3 as a composer setup? This error looks like the library `tinify` is missing. This library is loaded via `composer install`.

In the latest version of `tinyimg` a setup via extension manager is not supported anymore.
Solutions:
1. Setup your website via composer
2. Take care yourself of loading the library `tinify`

**Comment by arunspawoz** [comment]
Hi @schmitzal Happy New Year too :)

Thank you for your fast reply. Unfortunately, I am trying to implement the extension on an already existing live website. This installation is manual. So it is not easy to switch this.

Can you suggest any alternate solution for solving this case? So I can work on that.

Thank you for your valuable time.

Best Regards,
Arun

**Comment by schmitzal** [comment]
Hi @arunspawoz 

if you don't need any changes made in V. 1.3 ( see [here](https://github.com/schmitzal/tinyimg/blob/1.3.0/CHANGELOG.md) ), you could use V. 1.2 (only supported until TYPO3 8.7).

Else you'll have to upload the library manually and load it via `require_once` like [here](https://github.com/schmitzal/tinyimg/blob/1.2.0/Classes/Service/CompressImageService.php#L16).

**Comment by arunspawoz** [comment]
Hi @schmitzal 

Thank you very much. Let me try to upload the library manually and will try to load it.

Have a good day.

**Comment by schmitzal** [comment]
I'll close this one.
Just reopen if further support is needed.
