### ISSUE TITLE
PHP API for TYPO3 CMS Extension

### ISSUE THREAD

**Issue by simonwahlstrom** [schmitzal/tinyimg#5]
Hi Alex,

I'm one of the developers behind tinypng.com. We have been trying to answer your questions that you sent but our message keeps bouncing back. Could you provide me with an alternative email address either here or send us another message at support@tinypng.com?

**Comment by schmitzal** [comment]
Hi Simon,

wierd.. maybe I mistyped the email address..
It's alessandro.schmitz@interlutions.de

Thanks for answering :)
