### ISSUE TITLE
TYPO3 10 compatibility

### ISSUE THREAD

**Issue by breakone** [schmitzal/tinyimg#50]
I don't know if there is a chance of TYPO3 10 compatibility? Are there any plans of updating the extension?

**Comment by schmitzal** [comment]
Hi @breakone 

of course, there are plans. And thanks to contributions, there is already a DEV branch for v. 10.
The release will come out soon. Meanwhile just use the DEV branch, should work fine :)

Best

**Comment by schmitzal** [comment]
Release coming today
