### ISSUE TITLE
Manual installation of tinify PHP lib

### ISSUE THREAD

**Issue by chriskapeller** [schmitzal/tinyimg#51]
Hi, just curious where and how to install the Tinify Php Lib manually?
Cant use composer on this server! Where exactly to copy the php files?

Using the latest Typo3 extension for 10.4..

Thx
chriskapeller

**Comment by schmitzal** [comment]
Hi.
Here is the official documentation for autoloading without composer mode:
https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/Autoloading/Index.html#loading-classes-without-composer-mode

So it should be enough to download the source and place it in your project extension.

**Comment by schmitzal** [comment]
No feedback. Closed. Feel free to reopen
