### ISSUE TITLE
Tinyimg not displaying correct file size in Version 1.5.1

### ISSUE THREAD

**Issue by lorenzanmey** [schmitzal/tinyimg#55]
Since version 1.5.1 tinyimg shows "Tinyimg saved you about 0% of your file size!" for every image on TYPO3 8.7.33 (eLTS) after the compression.
If I open an image I see that the file size has changed and the compression did in fact work, but the information shown is wrong. Even the TYPO3 filelist module displays the original file size, not the compressed size.

**Comment by schmitzal** [comment]
Update: could reproduce the problem. looking for a solution

**Comment by schmitzal** [comment]
Bugfix released
