### ISSUE TITLE
Extend README.md: Compare database after installation

### ISSUE THREAD

**Issue by krausandre** [schmitzal/tinyimg#60]
For some reason, if you install the tinyimg ext via composer, you run in an error while trying to upload a file. It turned out, that if you have the `typo3cms install:generatepackagestates` in your composer.json scripts, but not the `typo3cms database:updateschema` the ext is installed but the database isn't up to date.
 
It would be helpful if this is mentioned in the install documentation.

**Comment by schmitzal** [comment]
Hi there,

that's just the normal behaviour of every TYPO3 extension. If you handle the extension installation by yourself you have to cary about packagestates and db. It's the same with news, gridelements or every other big or small TYPO3 extension :-)

Have a nice weekend!
