### ISSUE TITLE
Invalid Command::SUCCESS in CompressImagesCommand

### ISSUE THREAD

**Issue by px-flo** [schmitzal/tinyimg#70]
With Version 1.5.3 the return value of the execute-Method was changed to a class constant
`return Command::SUCCESS;`

This will use the class `\Symfony\Component\Console\Command\Command` which does not have such a constant. So the Command will produce an error. The TYPO3-Dependency in the composer.json ist set to `^10.4`

**Comment by schmitzal** [comment]
Which version of Symfony console component are you running? The current version has the constant.

**Comment by px-flo** [comment]
Currently i'm running
`            "name": "symfony/console",
            "version": "v4.4.26",`
I have not set the version by myself, this is the resulting version for typo3 10.4 with helhum/typo3-console.

The complete composer.json requirements of mine looks like the following:
`        "ext-zip": "*",
        "dirkpersky/typo3-dp_cookieconsent": "^10.6",
        "georgringer/news": "^8.5",
        "helhum/dotenv-connector": "^2.3",
        "helhum/typo3-console": "^6",
        "plan2net/webp": "^3.3",
        "roave/security-advisories": "dev-master",
        "schmitzal/tinyimg": "^1.5",
        "studiomitte/sendinblue": "^1.0",
        "t3monitor/t3monitoring_client": "dev-master",
        "typo3-console/composer-auto-commands": "^0.4",
        "typo3/cms-adminpanel": "^10.4",
        "typo3/cms-belog": "^10.4",
        "typo3/cms-beuser": "^10.4",
        "typo3/cms-context-help": "^10.4",
        "typo3/cms-dashboard": "^10.4",
        "typo3/cms-filelist": "^10.4",
        "typo3/cms-fluid-styled-content": "^10.4",
        "typo3/cms-form": "^10.4",
        "typo3/cms-impexp": "^10.4",
        "typo3/cms-info": "^10.4",
        "typo3/cms-info-pagetsconfig": "^10.4",
        "typo3/cms-lowlevel": "^10.4",
        "typo3/cms-recycler": "^10.4",
        "typo3/cms-redirects": "^10.4",
        "typo3/cms-reports": "^10.4",
        "typo3/cms-rte-ckeditor": "^10.4",
        "typo3/cms-scheduler": "^10.4",
        "typo3/cms-seo": "^10.4",
        "typo3/cms-setup": "^10.4",
        "typo3/cms-tstemplate": "^10.4",
        "typo3/cms-viewpage": "^10.4"`

I hope this helps.

**Comment by schmitzal** [comment]
Thanks. I'll change the return value, as TYPO3 10 supports version 4.4 and 5.3.

**Comment by px-flo** [comment]
I've made a pull-request ;) It's a simple solution :P
