### ISSUE TITLE
The 'sys_file' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed.

### ISSUE THREAD

**Issue by Alagts** [schmitzal/tinyimg#82]
We tried to update our web from TYPO3 v10.4.34 to v11.5.22. During the update phase we recognized that your extension tinyimg v1.6.1 is causing this message during the backend check "Check TCA Migrations": "The 'sys_file' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed." 
![Error_foreign_ext](https://user-images.githubusercontent.com/16323871/213145983-0666e101-6390-48f2-b246-2d00faa9dd3e.png)

**Comment by schmitzal** [comment]
Was not removed yet, as the extension still supports TYPO3 9 and "showRecordFieldList" has been deprecated in TYPO3 10.

Will be removed in the upcoming release for TYPO3 12.
