### ISSUE TITLE
TYPO3 12 compatibility

### ISSUE THREAD

**Issue by zenoussi** [schmitzal/tinyimg#86]
Hey!
Just wanted to ask if you plan to support TYPO3 v12 and if yes if you got a time plan for that?

Thanks a lot,
Ulli

**Comment by schmitzal** [comment]
Hi Ulli,

the extension already supports v12.
What is your issue with it?

Best,
Alex

**Comment by zenoussi** [comment]
> Hi Ulli,
> 
> the extension already supports v12. What is your issue with it?
> 
> Best, Alex

Oh no, I was just reading the outdated information in the TER, sorry. ✌🏼

**Comment by Fanor51** [comment]
Hello, 
quick reminder to put the right version into the TER - Run into the same issue ..  :D 

Best Regards
Fabio

**Comment by schmitzal** [comment]
Wow this took me a while... but wont happen again, as I've implemented a workflow to automatically push a new release to TER.

Thanks for you patience :D
