### ISSUE TITLE
Call to undefined function Tinify\setKey()

### ISSUE THREAD

**Issue by christophbee** [schmitzal/tinyimg#88]
Setup:
- TYPO3 v 12.4.14 (legacy installation)
- EXT:tinyimg v 1.7.0
- added the correct API key in extension settings: I am using the same API key in another project (composer installation with same versions) where it works.

When I upload an image via Filelist module the following error occurs:

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined function Tinify\setKey() | Error thrown in file /path/to/typo3/docroot/typo3conf/ext/tinyimg/Classes/Service/CompressImageService.php in line 72.`

![Bildschirmfoto 2024-05-18 um 07 08 32](https://github.com/schmitzal/tinyimg/assets/22295289/12d8e176-3d77-41f3-ae38-3c97ffcdef3a)

**Comment by schmitzal** [comment]
Hi,

full support for legacy installations has been dropped a couple of versions ago.

You need to take care of loading the Tinify library yourself. Download the source, add it to your site package or any local extension and load the classes.

Best,
Alex

**Comment by schmitzal** [comment]
Closed due missing response.

**Comment by nemstaa** [comment]
Hi Alex

I wanted to implement the Tinify-Class with their functions without a composer with no success.
I placed the files in "Resources/Private/Libraries/tinify" and tried it with the Services.yaml and ext_emconf.php (autoload + classmap):

`'autoload' => [
        'psr-4' => [
            'Vendor\\Namespace\\'=> 'Classes',
        ],
        'classmap' => ['Resources/Private/Libraries/tinify/lib/Tinify.php']
    ],`

Could you provide a solution or give me a hint for loading the Tinify-Lib in a seperate extension?

I would appreciate it.


Thank you in advance
Robert

**Comment by schmitzal** [comment]
Hi Robert,

it's difficult to provide any help with so little information.
Which TYPO3 version are you running?
I'm not sure how TYPO3 handles class mapping if those have namespaces.
I think the easiest way would be to add a new extension under the tinify namespace to you system.
But after all, why don't you switch to a composer based setup? Makes life so much easier 😄 

Aside from that, I think help requests like yours should be in the slack channel, as it's not an issue with the code:
https://typo3.slack.com/archives/C56P6PZ2S

Best
Alex

**Comment by nemstaa** [comment]
Hi Alex

Thank you for your answer.

I resolved the issue for me like this in the ext_localconf.php:

`<?php
defined('TYPO3_MODE') or die();

$boot = function () {
    if (TYPO3_MODE == 'BE') {

        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ext_key') . 'Resources/Private/PHP/tinify/lib/Tinify/Client.php';
        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ext_key') . 'Resources/Private/PHP/tinify/lib/Tinify/Exception.php';
        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ext_key') . 'Resources/Private/PHP/tinify/lib/Tinify/ResultMeta.php';
        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ext_key') . 'Resources/Private/PHP/tinify/lib/Tinify/Result.php';
        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('ext_key') . 'Resources/Private/PHP/tinify/lib/Tinify/Source.php';
        $composerAutoloadFiles[] = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('rw_misc') . 'Resources/Private/PHP/tinify/lib/Tinify.php';
        foreach($composerAutoloadFiles as $file) {
            require_once($file);
        }

    }

};
$boot();
unset($boot);`

Like you've said. The main thing was the namespace handle. TYPO3 created extra namespaces, while a function is executed in Tinify.php. 

I hope this helps those, who have the same case.

Thank you again.


Kind regards
Robert
