### ISSUE TITLE
TYPO3 13 compatibility

### ISSUE THREAD

**Issue by nanna-dk** [schmitzal/tinyimg#89]
Please make this extension compatible with TYPO3 13. Thank you very much!

**Comment by schmitzal** [comment]
Just pushed a dev version of the extension with support for TYPO3 13 (dev-v13).
Only tested basic upload which worked for me but no further testing until TYPO3 13 has a feature freeze.
Feel free to test it and comment if you find any issues.

**Comment by schmitzal** [comment]
Version for TYPO3 13 has been released past friday.
