### ISSUE TITLE
Add possibility to trigger the compression script for existing File Mount (s)

### ISSUE THREAD

**Issue by InvisibleKind** [schmitzal/tinyimg#9]
Hi,

It would be great to add a possibility to trigger scale for all existing images in selected filemount(s). Such a feature can be implemented as Scheduler Task.
Main use case for it: website is already running with tons of images, which need to be compressed.

**Comment by schmitzal** [comment]
Hey.

Thanks for your feature request. I'll have a look at it tomorrow, as I'm going to progress with version 1.1.0.

Best

**Comment by InvisibleKind** [comment]
Thank you for a fast response.
One thing came into my mind: the files in _processed_ folder should be ignored by such triggered compression script.

**Comment by schmitzal** [comment]
Of course, as this would fill the limit of compressions available in the tinypng account :)
But the processed files should be deleted, so they will be smaller in file size when generated again.
